version: '3'

volumes:
  workshop-rails-fake-api-history:

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3
        NODE_VERSION: lts/*
        HISTFOLDER: /history
    volumes:
      - .:/workspace:cached
      - workshop-rails-fake-api-history:/history

    # Overrides default command so things don't shut down after the process ends.
    command: zsh

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

