version: '3'

services:
  app:
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ~/.aws:/home/vscode/.aws:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
